// AUTO-GENERATED by scripts/generate_publications.py from
// src/data/publications.bib — do not edit by hand.

export interface PubEntry {
  id: string;
  authors: string[];
  title: string;
  url: string;
  source: string;
  year: string;
  award: string;
  code: string;
  bibtex: string;
}

export interface PubSection {
  key: string;
  heading: string;
  entries: PubEntry[];
}

export const publicationSections: PubSection[] = [
  {
    "key": "thesis",
    "heading": "PhD Thesis",
    "entries": [
      {
        "id": "@rodriguez2021thesis",
        "authors": [
          "Pedro Rodriguez"
        ],
        "title": "Evaluating Machine Intelligence with Question Answering",
        "url": "https://www.pedro.ai/static/publications/pedro_rodriguez_phd_thesis.pdf",
        "source": "University of Maryland, College Park",
        "year": "2021",
        "award": "",
        "code": "",
        "bibtex": "@phdthesis{rodriguez2021thesis,\n  author = {Pedro Rodriguez},\n  title = {Evaluating Machine Intelligence with Question Answering},\n  school = {University of Maryland, College Park},\n  year = {2021},\n  url = {https://www.pedro.ai/static/publications/pedro_rodriguez_phd_thesis.pdf},\n}"
      }
    ]
  },
  {
    "key": "publications",
    "heading": "Conference and Journal Papers",
    "entries": [
      {
        "id": "@pagnoni2025blt",
        "authors": [
          "Artidoro Pagnoni",
          "Ramakanth Pasunuru",
          "Pedro Rodriguez",
          "John Nguyen",
          "Benjamin Muller",
          "Margaret Li",
          "Chunting Zhou",
          "Lili Yu",
          "Jason Weston",
          "Luke Zettlemoyer",
          "Gargi Ghosh",
          "Mike Lewis",
          "Ari Holtzman",
          "Srinivasan Iyer"
        ],
        "title": "Byte Latent Transformer: Patches Scale Better Than Tokens",
        "url": "https://aclanthology.org/2025.acl-long.453",
        "source": "Annual Meeting of the Association for Computational Linguistics",
        "year": "2025",
        "award": "Outstanding Paper Award",
        "code": "https://github.com/facebookresearch/blt",
        "bibtex": "@inproceedings{pagnoni2025blt,\n  title = {Byte Latent Transformer: Patches Scale Better Than Tokens},\n  author = {Artidoro Pagnoni and Ramakanth Pasunuru and Pedro Rodriguez and John Nguyen and Benjamin Muller and Margaret Li and Chunting Zhou and Lili Yu and Jason Weston and Luke Zettlemoyer and Gargi Ghosh and Mike Lewis and Ari Holtzman and Srinivasan Iyer},\n  booktitle = {Annual Meeting of the Association for Computational Linguistics},\n  year = {2025},\n  url = {https://aclanthology.org/2025.acl-long.453},\n}"
      },
      {
        "id": "@lalor2024irttutorial",
        "authors": [
          "John P. Lalor",
          "Pedro Rodriguez",
          "João Sedoc",
          "José Hernández-Orallo"
        ],
        "title": "Item Response Theory for Natural Language Processing",
        "url": "https://aclanthology.org/2024.eacl-tutorials.2",
        "source": "Proceedings of the 18th Conference of the European Chapter of the Association for Computational Linguistics: Tutorial Abstracts",
        "year": "2024",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{lalor2024irttutorial,\n  title = {Item Response Theory for Natural Language Processing},\n  author = {John P. Lalor and Pedro Rodriguez and João Sedoc and José Hernández-Orallo},\n  booktitle = {Proceedings of the 18th Conference of the European Chapter of the Association for Computational Linguistics: Tutorial Abstracts},\n  year = {2024},\n  url = {https://aclanthology.org/2024.eacl-tutorials.2},\n}"
      },
      {
        "id": "@lee2024multimodal",
        "authors": [
          "Yejin Lee",
          "Anna Sun",
          "Basil Hosmer",
          "Bilge Acun",
          "Can Balioglu",
          "Changhan Wang",
          "Charles David Hernandez",
          "Christian Puhrsch",
          "Daniel Haziza",
          "Driss Guessous",
          "Francisco Massa",
          "Jacob Kahn",
          "Jeffrey Wan",
          "Jeremy Reizenstein",
          "Jiaqi Zhai",
          "Joe Isaacson",
          "Joel Schlosser",
          "Juan Pino",
          "Kaushik Ram Sadagopan",
          "Leonid Shamis",
          "Linjian Ma",
          "Min-Jae Hwang",
          "Mingda Chen",
          "Mostafa Elhoushi",
          "Pedro Rodriguez",
          "Ramakanth Pasunuru",
          "Scott Yih",
          "Sravya Popuri",
          "Xing Liu",
          "Carole-Jean Wu"
        ],
        "title": "Characterizing and Efficiently Accelerating Multimodal Generation Model Inference",
        "url": "https://arxiv.org/abs/2410.00215",
        "source": "IEEE Micro",
        "year": "2024",
        "award": "",
        "code": "",
        "bibtex": "@article{lee2024multimodal,\n  title = {Characterizing and Efficiently Accelerating Multimodal Generation Model Inference},\n  author = {Yejin Lee and Anna Sun and Basil Hosmer and Bilge Acun and Can Balioglu and Changhan Wang and Charles David Hernandez and Christian Puhrsch and Daniel Haziza and Driss Guessous and Francisco Massa and Jacob Kahn and Jeffrey Wan and Jeremy Reizenstein and Jiaqi Zhai and Joe Isaacson and Joel Schlosser and Juan Pino and Kaushik Ram Sadagopan and Leonid Shamis and Linjian Ma and Min-Jae Hwang and Mingda Chen and Mostafa Elhoushi and Pedro Rodriguez and Ramakanth Pasunuru and Scott Yih and Sravya Popuri and Xing Liu and Carole-Jean Wu},\n  journal = {IEEE Micro},\n  year = {2024},\n  url = {https://arxiv.org/abs/2410.00215},\n}"
      },
      {
        "id": "@wu2023simmcvr",
        "authors": [
          "Te-Lin Wu",
          "Satwik Kottur",
          "Andrea Madotto",
          "Mahmoud Azab",
          "Pedro Rodriguez",
          "Babak Damavandi",
          "Nanyun Peng",
          "Seungwhan Moon"
        ],
        "title": "SIMMC-VR: A Task-oriented Multimodal Dialog Dataset with Situated and Immersive VR Streams",
        "url": "https://aclanthology.org/2023.acl-long.345",
        "source": "Annual Meeting of the Association for Computational Linguistics",
        "year": "2023",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{wu2023simmcvr,\n  title = {{SIMMC-VR}: A Task-oriented Multimodal Dialog Dataset with Situated and Immersive {VR} Streams},\n  author = {Te-Lin Wu and Satwik Kottur and Andrea Madotto and Mahmoud Azab and Pedro Rodriguez and Babak Damavandi and Nanyun Peng and Seungwhan Moon},\n  booktitle = {Annual Meeting of the Association for Computational Linguistics},\n  year = {2023},\n  url = {https://aclanthology.org/2023.acl-long.345},\n}"
      },
      {
        "id": "@tan2023reimagining",
        "authors": [
          "Wang-Chiew Tan",
          "Yuliang Li",
          "Pedro Rodriguez",
          "Richard James",
          "Xi Victoria Lin",
          "Alon Halevy",
          "Scott Yih"
        ],
        "title": "Reimagining Retrieval Augmented Language Models for Answering Queries",
        "url": "https://aclanthology.org/2023.findings-acl.382",
        "source": "Findings of the Association for Computational Linguistics: ACL 2023",
        "year": "2023",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{tan2023reimagining,\n  title = {Reimagining Retrieval Augmented Language Models for Answering Queries},\n  author = {Wang-Chiew Tan and Yuliang Li and Pedro Rodriguez and Richard James and Xi Victoria Lin and Alon Halevy and Scott Yih},\n  booktitle = {Findings of the Association for Computational Linguistics: ACL 2023},\n  year = {2023},\n  url = {https://aclanthology.org/2023.findings-acl.382},\n}"
      },
      {
        "id": "@rodriguez2023fire",
        "authors": [
          "Pedro Rodriguez",
          "Mahmoud Azab",
          "Becka Silvert",
          "Renato Sanchez",
          "Linzy Labson",
          "Hardik Shah",
          "Seungwhan Moon"
        ],
        "title": "Fighting FIRe with FIRE: Assessing the Validity of Text-to-Video Retrieval Benchmarks",
        "url": "http://arxiv.org/abs/2210.05038",
        "source": "Findings of the European Chapter of the Association for Computational Linguistics",
        "year": "2023",
        "award": "",
        "code": "https://github.com/facebookresearch/mm-retrieval-evaluation",
        "bibtex": "@inproceedings{rodriguez2023fire,\n  title = {Fighting {FIRe} with {FIRE}: Assessing the Validity of {Text-to-Video} Retrieval Benchmarks},\n  author = {Pedro Rodriguez and Mahmoud Azab and Becka Silvert and Renato Sanchez and Linzy Labson and Hardik Shah and Seungwhan Moon},\n  year = {2023},\n  url = {http://arxiv.org/abs/2210.05038},\n  booktitle = {Findings of the European Chapter of the Association for Computational Linguistics},\n}"
      },
      {
        "id": "@thrush2022dynatask",
        "authors": [
          "Tristan Thrush",
          "Kushal Tirumala",
          "Anmol Gupta",
          "Max Bartolo",
          "Pedro Rodriguez",
          "Tariq Kane",
          "William Gaviria Rojas",
          "Peter Mattson",
          "Adina Williams",
          "Douwe Kiela"
        ],
        "title": "Dynatask: A Framework for Creating Dynamic AI Benchmark Tasks",
        "url": "https://aclanthology.org/2022.acl-demo.17",
        "source": "Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics: System Demonstrations",
        "year": "2022",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{thrush2022dynatask,\n  title = {Dynatask: A Framework for Creating Dynamic {AI} Benchmark Tasks},\n  author = {Tristan Thrush and Kushal Tirumala and Anmol Gupta and Max Bartolo and Pedro Rodriguez and Tariq Kane and William Gaviria Rojas and Peter Mattson and Adina Williams and Douwe Kiela},\n  booktitle = {Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics: System Demonstrations},\n  year = {2022},\n  publisher = {Association for Computational Linguistics},\n  url = {https://aclanthology.org/2022.acl-demo.17},\n}"
      },
      {
        "id": "@lalor2022pyirt",
        "authors": [
          "John P. Lalor",
          "Pedro Rodriguez"
        ],
        "title": "PY-IRT: A Scalable Item Response Theory Library for Python",
        "url": "https://doi.org/10.1287/ijoc.2022.1250",
        "source": "INFORMS Journal on Computing",
        "year": "2022",
        "award": "",
        "code": "https://github.com/nd-ball/py-irt",
        "bibtex": "@article{lalor2022pyirt,\n  title = {PY-IRT: A Scalable Item Response Theory Library for Python},\n  author = {John P. Lalor and Pedro Rodriguez},\n  year = {2022},\n  journal = {{INFORMS} Journal on Computing},\n  publisher = {Institute for Operations Research and the Management Sciences ({INFORMS})},\n  doi = {10.1287/ijoc.2022.1250},\n  url = {https://doi.org/10.1287/ijoc.2022.1250},\n}"
      },
      {
        "id": "@rodriguez2021paradigms",
        "authors": [
          "Pedro Rodriguez",
          "Jordan Boyd-Graber"
        ],
        "title": "Evaluation Paradigms in Question Answering",
        "url": "https://research.fb.com/publications/evaluation-paradigms-in-question-answering/",
        "source": "Empirical Methods in Natural Language Processing",
        "year": "2021",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{rodriguez2021paradigms,\n  author = {Pedro Rodriguez and Jordan Boyd-Graber},\n  title = {Evaluation Paradigms in Question Answering},\n  year = {2021},\n  booktitle = {Empirical Methods in Natural Language Processing},\n  publisher = {Association for Computational Linguistics},\n  url = {https://research.fb.com/publications/evaluation-paradigms-in-question-answering/},\n}"
      },
      {
        "id": "@rodriguez2020leaderboard",
        "authors": [
          "Pedro Rodriguez",
          "Joe Barrow",
          "Alexander Hoyle",
          "John P. Lalor",
          "Robin Jia",
          "Jordan Boyd-Graber"
        ],
        "title": "Evaluation Examples Are Not Equally Informative: How Should That Change NLP Leaderboards?",
        "url": "https://aclanthology.org/2021.acl-long.346",
        "source": "Association for Computational Linguistics",
        "year": "2021",
        "award": "",
        "code": "https://github.com/facebookresearch/irt-leaderboard",
        "bibtex": "@inproceedings{rodriguez2020leaderboard,\n  author = {Pedro Rodriguez and Joe Barrow and Alexander Hoyle and John P. Lalor and Robin Jia and Jordan Boyd-Graber},\n  title = {Evaluation Examples Are Not Equally Informative: How Should That Change {NLP} Leaderboards?},\n  year = {2021},\n  booktitle = {Association for Computational Linguistics},\n  publisher = {Association for Computational Linguistics},\n  url = {https://aclanthology.org/2021.acl-long.346},\n  doi = {10.18653/v1/2021.acl-long.346},\n}"
      },
      {
        "id": "@rodriguez2020curiosity",
        "authors": [
          "Pedro Rodriguez",
          "Paul Crook",
          "Seungwhan Moon",
          "Zhiguang Wang"
        ],
        "title": "Information Seeking in the Spirit of Learning: a Dataset for Conversational Curiosity",
        "url": "https://www.pedro.ai/static/publications/2020_emnlp_curiosity.paper.pdf",
        "source": "Empirical Methods in Natural Language Processing",
        "year": "2020",
        "award": "",
        "code": "https://github.com/facebookresearch/curiosity",
        "bibtex": "@inproceedings{rodriguez2020curiosity,\n  author = {Pedro Rodriguez and Paul Crook and Seungwhan Moon and Zhiguang Wang},\n  title = {Information Seeking in the Spirit of Learning: a Dataset for Conversational Curiosity},\n  year = {2020},\n  url = {https://www.pedro.ai/static/publications/2020_emnlp_curiosity.paper.pdf},\n  booktitle = {Empirical Methods in Natural Language Processing},\n}"
      },
      {
        "id": "@Wallace:Rodriguez:Feng:Yamada:Boyd-Graber-2019",
        "authors": [
          "Eric Wallace",
          "Pedro Rodriguez",
          "Shi Feng",
          "Ikuya Yamada",
          "Jordan Boyd-Graber"
        ],
        "title": "Trick Me If You Can: Human-in-the-loop Generation of Adversarial Question Answering Examples",
        "url": "https://www.pedro.ai/static/publications/2019_tacl_trick.pdf",
        "source": "Transactions of the Association of Computational Linguistics",
        "year": "2019",
        "award": "",
        "code": "",
        "bibtex": "@article{Wallace:Rodriguez:Feng:Yamada:Boyd-Graber-2019,\n  title = {Trick Me If You Can: Human-in-the-loop Generation of Adversarial Question Answering Examples},\n  author = {Eric Wallace and Pedro Rodriguez and Shi Feng and Ikuya Yamada and Jordan Boyd-Graber},\n  journal = {Transactions of the Association of Computational Linguistics},\n  year = {2019},\n  volume = {10},\n  url = {https://www.pedro.ai/static/publications/2019_tacl_trick.pdf},\n}"
      },
      {
        "id": "@Peskov:Barrow:Rodriguez:Neubig:Boyd-Graber-2019",
        "authors": [
          "Denis Peskov",
          "Joe Barrow",
          "Pedro Rodriguez",
          "Graham Neubig",
          "Jordan Boyd-Graber"
        ],
        "title": "Mitigating Noisy Inputs for Question Answering",
        "url": "http://dx.doi.org/10.21437/Interspeech.2019-3154",
        "source": "Interspeech",
        "year": "2019",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{Peskov:Barrow:Rodriguez:Neubig:Boyd-Graber-2019,\n  author = {Denis Peskov and Joe Barrow and Pedro Rodriguez and Graham Neubig and Jordan Boyd-Graber},\n  title = {Mitigating Noisy Inputs for Question Answering},\n  booktitle = {Interspeech},\n  year = {2019},\n  doi = {10.21437/Interspeech.2019-3154},\n  url = {http://dx.doi.org/10.21437/Interspeech.2019-3154},\n}"
      },
      {
        "id": "@feng2018rawr",
        "authors": [
          "Shi Feng",
          "Eric Wallace",
          "Alvin Grissom II",
          "Mohit Iyyer",
          "Pedro Rodriguez",
          "Jordan Boyd-Graber"
        ],
        "title": "Pathologies of Neural Models Make Interpretations Difficult",
        "url": "https://arxiv.org/abs/1804.07781",
        "source": "Empirical Methods in Natural Language Processing",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{feng2018rawr,\n  title = {Pathologies of Neural Models Make Interpretations Difficult},\n  author = {Shi Feng and Eric Wallace and Alvin Grissom II and Mohit Iyyer and Pedro Rodriguez and Jordan Boyd-Graber},\n  booktitle = {Empirical Methods in Natural Language Processing},\n  year = {2018},\n  url = {https://arxiv.org/abs/1804.07781},\n}"
      },
      {
        "id": "@Boyd-Graber:Feng:Rodriguez-2018",
        "authors": [
          "Jordan Boyd-Graber",
          "Shi Feng",
          "Pedro Rodriguez"
        ],
        "title": "Human-Computer Question Answering: The Case for Quizbowl",
        "url": "https://www.pedro.ai/static/publications/2018_nips_qbcomp.pdf",
        "source": "The NIPS '17 Competition: Building Intelligent Systems",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@inbook{Boyd-Graber:Feng:Rodriguez-2018,\n  title = {Human-Computer Question Answering: The Case for Quizbowl},\n  author = {Jordan Boyd-Graber and Shi Feng and Pedro Rodriguez},\n  publisher = {Springer Verlag},\n  year = {2018},\n  editor = {Sergio Escalera and Markus Weimer},\n  booktitle = {The NIPS '17 Competition: Building Intelligent Systems},\n  url = {https://www.pedro.ai/static/publications/2018_nips_qbcomp.pdf},\n}"
      }
    ]
  },
  {
    "key": "arxiv",
    "heading": "arXiv",
    "entries": [
      {
        "id": "@chameleon2024",
        "authors": [
          "Chameleon Team"
        ],
        "title": "Chameleon: Mixed-Modal Early-Fusion Foundation Models",
        "url": "https://arxiv.org/abs/2405.09818",
        "source": "arXiv",
        "year": "2024",
        "award": "",
        "code": "https://github.com/facebookresearch/chameleon",
        "bibtex": "@article{chameleon2024,\n  title = {Chameleon: Mixed-Modal Early-Fusion Foundation Models},\n  author = {Chameleon Team},\n  booktitle = {arXiv},\n  year = {2024},\n  url = {https://arxiv.org/abs/2405.09818},\n}"
      },
      {
        "id": "@qanta2019",
        "authors": [
          "Pedro Rodriguez",
          "Shi Feng",
          "Mohit Iyyer",
          "He He",
          "Jordan Boyd-Graber"
        ],
        "title": "Quizbowl: The Case for Incremental Question Answering",
        "url": "https://arxiv.org/abs/1904.04792",
        "source": "arXiv",
        "year": "2019",
        "award": "",
        "code": "https://github.com/Pinafore/qb",
        "bibtex": "@article{qanta2019,\n  title = {Quizbowl: The Case for Incremental Question Answering},\n  author = {Pedro Rodriguez and Shi Feng and Mohit Iyyer and He He and Jordan Boyd-Graber},\n  year = {2019},\n  eprint = {arXiv:1904.04792},\n  url = {https://arxiv.org/abs/1904.04792},\n  booktitle = {arXiv},\n}"
      }
    ]
  },
  {
    "key": "workshops",
    "heading": "Workshop Papers",
    "entries": [
      {
        "id": "@rodriguez2022clustering",
        "authors": [
          "Pedro Rodriguez",
          "Phu Mon Htut",
          "John P. Lalor",
          "João Sedoc"
        ],
        "title": "Clustering Examples in Multi-Dataset Benchmarks with Item Response Theory",
        "url": "https://aclanthology.org/2022.insights-1.14",
        "source": "Proceedings of the Third Workshop on Insights from Negative Results in NLP",
        "year": "2022",
        "award": "",
        "code": "https://github.com/entilzha/multidim-irt",
        "bibtex": "@inproceedings{rodriguez2022clustering,\n  title = {Clustering Examples in Multi-Dataset Benchmarks with Item Response Theory},\n  author = {Pedro Rodriguez and Phu Mon Htut and John P. Lalor and Joao Sedoc},\n  booktitle = {Proceedings of the Third Workshop on Insights from Negative Results in NLP},\n  year = {2022},\n  publisher = {Association for Computational Linguistics},\n  url = {https://aclanthology.org/2022.insights-1.14},\n}"
      },
      {
        "id": "@raman2020quel",
        "authors": [
          "Naveen Raman",
          "Pedro Rodriguez",
          "Jordan Boyd-Graber"
        ],
        "title": "What more can Entity Linking do for Question Answering?",
        "url": "https://openreview.net/forum?id=grMp1hsIbTg",
        "source": "NeurIPS 2020 Workshop on Human And Model in the Loop Evaluation and Training Strategies",
        "year": "2020",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{raman2020quel,\n  title = {What more can Entity Linking do for Question Answering?},\n  author = {Naveen Raman and Pedro Rodriguez and Jordan Boyd-Graber},\n  booktitle = {{NeurIPS} 2020 Workshop on Human And Model in the Loop Evaluation and Training Strategies},\n  year = {2020},\n  url = {https://openreview.net/forum?id=grMp1hsIbTg},\n}"
      },
      {
        "id": "@classificationSnow",
        "authors": [
          "Santiago Rodriguez",
          "Pedro Rodriguez"
        ],
        "title": "Classification of snow anisotropic surfaces for mountainous terrain with mixed vegetative cover using optical and thermal spectra from Landsat-8",
        "url": "https://arc.lib.montana.edu/snow-science/objects/ISSW2018_P04.4.pdf",
        "source": "Proceedings of the 2018 International Snow Science Workshop",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{classificationSnow,\n  author = {Santiago Rodriguez and Pedro Rodriguez},\n  title = {Classification of snow anisotropic surfaces for mountainous terrain with mixed vegetative cover using optical and thermal spectra from Landsat-8},\n  booktitle = {Proceedings of the 2018 International Snow Science Workshop},\n  year = {2018},\n  url = {https://arc.lib.montana.edu/snow-science/objects/ISSW2018_P04.4.pdf},\n}"
      },
      {
        "id": "@bitacora",
        "authors": [
          "Santiago Rodriguez",
          "Pedro Rodriguez",
          "Bryan Biggs"
        ],
        "title": "Ski Touring Bitacora - An innovative approach for trip planning, recording observations, and risk management while traveling in Avalanche terrain",
        "url": "https://arc.lib.montana.edu/snow-science/objects/ISSW2018_P18.4.pdf",
        "source": "Proceedings of the 2018 International Snow Science Workshop",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{bitacora,\n  author = {Santiago Rodriguez and Pedro Rodriguez and Bryan Biggs},\n  title = {Ski Touring Bitacora - An innovative approach for trip planning, recording observations, and risk management while traveling in Avalanche terrain},\n  booktitle = {Proceedings of the 2018 International Snow Science Workshop},\n  year = {2018},\n  url = {https://arc.lib.montana.edu/snow-science/objects/ISSW2018_P18.4.pdf},\n}"
      },
      {
        "id": "@rodriguez2018kbandradar",
        "authors": [
          "Santiago Rodriguez",
          "Hans Peter Marshall",
          "Pedro Rodriguez"
        ],
        "title": "Application of a K-band FMCW Radar for the temporal tracking of dry snow stratigraphy, snowpack melt-freeze states, and mixed snow-rain precipitation events",
        "url": "",
        "source": "",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{rodriguez2018kbandradar,\n  author = {Santiago Rodriguez and Hans Peter Marshall and Pedro Rodriguez},\n  title = {Application of a K-band FMCW Radar for the temporal tracking of dry snow stratigraphy, snowpack melt-freeze states, and mixed snow-rain precipitation events},\n  year = {2018},\n}"
      },
      {
        "id": "@stabilityWheel",
        "authors": [
          "Pedro Rodriguez",
          "Santiago Rodriguez",
          "Julian Carielo"
        ],
        "title": "The Stability Wheel: An Intuitive and Didactic Decision-Making Framework",
        "url": "http://arc.lib.montana.edu/snow-science/objects/ISSW14_paper_P4.34.pdf",
        "source": "Proceedings of the 2014 International Snow Science Workshop",
        "year": "2014",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{stabilityWheel,\n  author = {Pedro Rodriguez and Santiago Rodriguez and Julian Carielo},\n  title = {The Stability Wheel: An Intuitive and Didactic Decision-Making Framework},\n  booktitle = {Proceedings of the 2014 International Snow Science Workshop},\n  year = {2014},\n  url = {http://arc.lib.montana.edu/snow-science/objects/ISSW14_paper_P4.34.pdf},\n}"
      },
      {
        "id": "@lowradar",
        "authors": [
          "Santiago Rodriguez",
          "Hans Peter Marshall",
          "Pedro Rodriguez"
        ],
        "title": "Applications of Low Cost and Low Power FMCW Radar in the Characterization of Dry Snow",
        "url": "http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.977.7907&rep=rep1&type=pdf",
        "source": "Proceedings of the 2014 International Snow Science Workshop",
        "year": "2014",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{lowradar,\n  author = {Santiago Rodriguez and Hans Peter Marshall and Pedro Rodriguez},\n  title = {Applications of Low Cost and Low Power FMCW Radar in the Characterization of Dry Snow},\n  booktitle = {Proceedings of the 2014 International Snow Science Workshop},\n  year = {2014},\n  url = {http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.977.7907&rep=rep1&type=pdf},\n}"
      }
    ]
  },
  {
    "key": "nonRefereed",
    "heading": "Non-Refereed",
    "entries": [
      {
        "id": "@2013AAS...22135428R",
        "authors": [
          "Pedro Rodriguez",
          "Joshua S. Bloom",
          "Joseph W. Richards"
        ],
        "title": "Cross Matching MACC and ROSAT: Characterization of Matching and Resulting Class Trends",
        "url": "http://adsabs.harvard.edu/abs/2013AAS...22135428R",
        "source": "American Astronomical Society Meeting Abstracts #221",
        "year": "2013",
        "award": "",
        "code": "",
        "bibtex": "@inproceedings{2013AAS...22135428R,\n  author = {Pedro Rodriguez and Joshua S. Bloom and Joseph W. Richards},\n  title = {Cross Matching MACC and ROSAT: Characterization of Matching and Resulting Class Trends},\n  booktitle = {American Astronomical Society Meeting Abstracts #221},\n  year = {2013},\n  series = {American Astronomical Society Meeting Abstracts},\n  volume = {221},\n  month = {jan},\n  eid = {354.28},\n  pages = {354.28},\n  adsurl = {http://adsabs.harvard.edu/abs/2013AAS...22135428R},\n  adsnote = {Provided by the SAO/NASA Astrophysics Data System},\n  url = {http://adsabs.harvard.edu/abs/2013AAS...22135428R},\n}"
      }
    ]
  },
  {
    "key": "media",
    "heading": "Media",
    "entries": [
      {
        "id": "@pathologies",
        "authors": [
          "Matthew Wright"
        ],
        "title": "New method peeks inside the 'black box' of artificial intelligence",
        "url": "https://www.eurekalert.org/pub_releases/2018-10/uom-nmp103118.php",
        "source": "EurekAlert",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@online{pathologies,\n  journal = {EurekAlert},\n  url = {https://www.eurekalert.org/pub_releases/2018-10/uom-nmp103118.php},\n  author = {Matthew Wright},\n  year = {2018},\n  title = {New method peeks inside the 'black box' of artificial intelligence},\n}"
      },
      {
        "id": "@Katabuti-2018",
        "authors": [
          "Yomihiro Katabuti"
        ],
        "title": "The Impact of Fast-Moving AI: Dominating Trivia Champs",
        "url": "http://www.itmedia.co.jp/news/articles/1802/28/news037.html",
        "source": "IT Media",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@online{Katabuti-2018,\n  journal = {IT Media},\n  url = {http://www.itmedia.co.jp/news/articles/1802/28/news037.html},\n  author = {Yomihiro Katabuti},\n  year = {2018},\n  title = {The Impact of Fast-Moving AI: Dominating Trivia Champs},\n}"
      },
      {
        "id": "@Brachfeld-2017",
        "authors": [
          "Melissa Brachfeld"
        ],
        "title": "UMD Computerized System Beats Human Quiz Bowl Team at Atlanta Exhibition",
        "url": "https://www.umiacs.umd.edu/about-us/news/umd-computerized-system-beats-human-quiz-bowl-team-atlanta-exhibition",
        "source": "UMIACS",
        "year": "2017",
        "award": "",
        "code": "",
        "bibtex": "@online{Brachfeld-2017,\n  journal = {UMIACS},\n  url = {https://www.umiacs.umd.edu/about-us/news/umd-computerized-system-beats-human-quiz-bowl-team-atlanta-exhibition},\n  author = {Melissa Brachfeld},\n  year = {2017},\n  title = {UMD Computerized System Beats Human Quiz Bowl Team at Atlanta Exhibition},\n}"
      },
      {
        "id": "@Yamada:Boyd-Graber:Rodriguez-2017",
        "authors": [
          "Ikuya Yamada",
          "Jordan Boyd-Graber",
          "Pedro Rodriguez"
        ],
        "title": "OUSIA vs. Trivia All-Stars",
        "url": "https://www.youtube.com/watch?v=PdfxUQNE46M",
        "source": "",
        "year": "2017",
        "award": "",
        "code": "",
        "bibtex": "@online{Yamada:Boyd-Graber:Rodriguez-2017,\n  url = {https://www.youtube.com/watch?v=PdfxUQNE46M},\n  year = {2017},\n  author = {Ikuya Yamada and Jordan Boyd-Graber and Pedro Rodriguez},\n  location = {Long Beach, CA},\n  title = {OUSIA vs. Trivia All-Stars},\n}"
      }
    ]
  },
  {
    "key": "projects",
    "heading": "Course Projects",
    "entries": [
      {
        "id": "@vision",
        "authors": [
          "Pedro Rodriguez",
          "Mozhi Zhang"
        ],
        "title": "Zero-Shot Learning from Wikipedia Descriptions",
        "url": "https://www.pedro.ai/static/publications/vision.pdf",
        "source": "UMD Course Project - CMSC828I",
        "year": "2018",
        "award": "",
        "code": "",
        "bibtex": "@online{vision,\n  title = {Zero-Shot Learning from Wikipedia Descriptions},\n  author = {Pedro Rodriguez and Mozhi Zhang},\n  year = {2018},\n  url = {https://www.pedro.ai/static/publications/vision.pdf},\n  booktitle = {UMD Course Project - CMSC828I},\n}"
      },
      {
        "id": "@networks",
        "authors": [
          "Pedro Rodriguez",
          "Fenfei Guo"
        ],
        "title": "Using the Wikipedia Game to Play Trivia Games",
        "url": "https://www.pedro.ai/static/publications/networks.pdf",
        "source": "CUB Course Project - CSCI 5352",
        "year": "2016",
        "award": "",
        "code": "",
        "bibtex": "@online{networks,\n  title = {Using the Wikipedia Game to Play Trivia Games},\n  author = {Pedro Rodriguez and Fenfei Guo},\n  year = {2016},\n  url = {https://www.pedro.ai/static/publications/networks.pdf},\n  booktitle = {CUB Course Project - CSCI 5352},\n}"
      }
    ]
  }
];
